** MoviesSearch
This app uses React.js for rendering real time search results for all your
favorite movies.

** Dependencies
You need npm/yarn installed in your local machine in order to run this app.

** Installation

#+BEGIN_SRC bash
npm install
npm start
#+END_SRC

** Claim an Issue
Comment on the issue. In case of no activity on the issue even after 2 days, the
issue will be reassigned. If you have difficulty approaching the issue, feel
free to ask on our slack channel.

** Communication
If you have any queries or suggestions, please use the slack channel.

** Guidelines
Please help us follow the best practice to make it easy for the reviewer as well
as the contributor. We want to focus on the code quality more than on managing
pull request ethics.
1. People before code: If any of the following rules are violated, the
   pull-requests must not be rejected. This is to create an easy and joyful
   onboarding process for new programmers and first-time contributors.
2. Single commit per pull request and name the commit as something meaningful,
   example: Adding <-your-name-> in students/mentors section.
3. Reference the issue numbers in the commit message if it resolves an open
   issue. Follow the pattern Fixes #
4. Make a note to add relevent Screen Shots when you make a PR.
5. Pull Request older than 3 days with no response from the contributor shall be
   marked closed.
6. Do not make PR which is not related to any issues. You can create an issue
   and solve it once we approve them.
7. Avoid duplicate PRs, if need be comment on the older PR with the PR number of
   the follow-up (new PR) and close the obsolete PR yourself.
8. Be polite: Be polite to other community members.
9. PR template should be strictly followed, else the points won't be reflected
   on the leaderboard.

/Happy coding./
